"""
Metorial Core SDK - Internal implementation
Generally not for public use: use 'metorial' package instead
"""

# Import everything from main module
from .main import (
  Metorial,
  MetorialSync,
  MetorialBase,
  MetorialError,
  MetorialSDKError,
  MetorialAPIError,
  MetorialToolError,
  MetorialTimeoutError,
  MetorialDuplicateToolError,
  StreamEvent,
  StreamEventType,
  ChatMetrics,
  ToolManager,
  CacheInfo,
  ToolStatistics,
  OpenAITool,
  MetorialTool,
  MetorialSession,
  SessionFactory,
  ToolFormatAdapter,
  ToolSanitizer,
  MetorialConfig,
  ProviderConfig,
  load_config_from_env,
  get_provider_config,
  validate_config,
  print_config_status,
  ProviderAdapter,
  ChatMessage,
  ChatResponse,
  OpenAIAdapter,
  AnthropicAdapter,
  GoogleAdapter,
  MistralAdapter,
  DeepSeekAdapter,
  TogetherAIAdapter,
  XAIAdapter,
  OpenAICompatibleAdapter,
  create_provider_adapter,
  infer_provider_type,
  MetorialSDKBuilder,
  SDKConfig,
  SDK,
  create_metorial_sdk,
  create_auth_headers,
  TypedMetorialServersEndpoint,
  TypedMetorialSessionsEndpoint,
)

# Import Group classes separately to avoid circular imports
from .sdk import (
  ServersGroup,
  SessionsGroup,
  ProviderOauthGroup,
  ProviderOauthConnectionsGroup,
  RunsGroup,
)

# Import additional typed endpoints
from .typed_endpoints import (
  TypedMetorialProviderOauthEndpoint,
  TypedMetorialProviderOauthConnectionsEndpoint,
)

__version__ = "1.0.0"

__all__ = [
  "Metorial",
  "MetorialSync",
  "MetorialBase",
  "MetorialError",
  "MetorialSDKError",
  "MetorialAPIError",
  "MetorialToolError",
  "MetorialTimeoutError",
  "MetorialDuplicateToolError",
  "StreamEvent",
  "StreamEventType",
  "ChatMetrics",
  "ToolManager",
  "CacheInfo",
  "ToolStatistics",
  "OpenAITool",
  "MetorialTool",
  "MetorialSession",
  "SessionFactory",
  "ToolFormatAdapter",
  "ToolSanitizer",
  "MetorialConfig",
  "ProviderConfig",
  "load_config_from_env",
  "get_provider_config",
  "validate_config",
  "print_config_status",
  "ProviderAdapter",
  "ChatMessage",
  "ChatResponse",
  "OpenAIAdapter",
  "AnthropicAdapter",
  "GoogleAdapter",
  "MistralAdapter",
  "DeepSeekAdapter",
  "TogetherAIAdapter",
  "XAIAdapter",
  "OpenAICompatibleAdapter",
  "create_provider_adapter",
  "infer_provider_type",
  "MetorialSDKBuilder",
  "SDKConfig",
  "SDK",
  "create_metorial_sdk",
  "create_auth_headers",
  # Group classes for type checking
  "ServersGroup",
  "SessionsGroup",
  "ProviderOauthGroup",
  "ProviderOauthConnectionsGroup",
  "RunsGroup",
  # Typed endpoint classes
  "TypedMetorialServersEndpoint",
  "TypedMetorialSessionsEndpoint",
  "TypedMetorialProviderOauthEndpoint",
  "TypedMetorialProviderOauthConnectionsEndpoint",
  "__version__",
]
