{% set version = environ.get('GIT_TAG', '0.0.0').lstrip('v') %}
{% set build   = environ.get('BUILD_NUMBER', '0') %}

package:
  name: metorial
  version: {{ version }}

source:
  path: ../packages/metorial

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0 
    - wheel             
  run:
    - python >=3.8
    - aiohttp >=3.8.0
    - typing-extensions >=4.0.0

test:
  commands:
    - python -c "import metorial"

about:
  home: "https://metorial.com"
  doc_url: "https://metorial.com/docs"
  dev_url: "https://github.com/metorial/metorial/clients/metorial-py"
  license: MIT
  license_file: LICENSE
  summary: "Python SDK for Metorial - AI tool calling and session management"

extra:
  recipe-maintainers:
    - RahmeKarim